test_that("mylm works", {
  library(plyr)
  lm.my1 <- mylm(mpg~cyl+disp, data = mtcars)
  lm.original1 <- lm(mpg~cyl+disp, data = mtcars)
  expect_equal(lm.my1$coefficients$Estimate,as.vector(lm.original1$coefficients))
  expect_equal(as.vector(lm.my1$residuals),as.vector(lm.original1$residuals))
  expect_equal(as.vector(lm.my1$fitted.values),as.vector(lm.original1$fitted.values))
  expect_equal(as.vector(lm.my1$rank),as.vector(lm.original1$rank))
  lm.my2 <- mylm(mpg~cyl+disp, data = mtcars, useSparse = T)
  expect_equal(lm.my2$coefficients$Estimate,as.vector(lm.original1$coefficients))
  expect_equal(as.vector(lm.my2$residuals),as.vector(lm.original1$residuals))
  expect_equal(as.vector(lm.my2$fitted.values),as.vector(lm.original1$fitted.values))
  expect_equal(as.vector(lm.my2$rank),as.vector(lm.original1$rank))
})
